---
title: "Codebook - Run_Analysis.R - UCI HAR Dataset"
author: "Alexandra Mackey"
date: "22-Nov-2015"
output:
  html_document:
    keep_md: yes
---

## Project Description
This function cleans the UCI HAR Dataset into a usable form and calculates the mean for each variable. 

##Study design and data processing

###Collection of the raw data
The data used is available at: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

It was collected by Smartlab - Non Linear Complex Systems Laboratory at DITEN - Universit‡ degli Studi di Genova.

30 volunteers wore a Samsung Galaxy S II smartphone while performing 6 activities (walking, walking upstairs, walking downstairs, laying, sitting, and standing). The embedded accelerometer and gyroscope recorded velocity and acceleration information. 

###Notes on the original (raw) data 
The data was pre-preocessed with noise filters and sliding windows. The acceleration data was seperated into gravitational and body motion components.  The data is also split into two sections: training and test data. 

##Creating the tidy datafile

###Guide to create the tidy data file
Prior to running the function:
1. Download the data. 
2. Unzip the data to a local folder. 
3. Set the R working directory to the folder containing the unzipped UCI HAR Dataset folder. 
4. Import the run_analysis script into R. 
5. Run run_analysis().

###Cleaning of the data
The run analysis merges all of the relevant tables in the UCI HAR Dataset together such that each measurement is associate with one Subject ID and one Activity Number/Label and the table is labeled in an easily understandable manner. The dataset is then subest to include only mean and standard deviation variables. Calculations then produce a final table (tidy_data.txt) that includes the mean of each measured variable for each Subject performing each Activity. 

The code is described in further detail at: 

##Description of the variables in the tidy_data.txt file

The dimensions of the dataset are 180 rows and 89 columns. 

A summary of each variable is provided within each variable's section of this document. 

Each row represents one Subject completing one Activity. There are 6 rows for each Subject and 30 rows for each Activity for a total of 180 rows.

The first three columns indicate identify the Subject (SubjectID), and the Activity (ActivityNumber and ActivityLabel). Both the ActivityNumber and the ActivityLabel were included in the final table to account for potential needs of future users. 

The additional columns then inlcudes a mean value for each of the following variables: 
"tBodyAcc_mean_X", "tBodyAcc_mean_Y", "tBodyAcc_mean_Z", "tBodyAcc_std_X", "tBodyAcc_std_Y", "tBodyAcc_std_Z", "tGravityAcc_mean_X", "tGravityAcc_mean_Y", "tGravityAcc_mean_Z", "tGravityAcc_std_X", "tGravityAcc_std_Y", "tGravityAcc_std_Z", "tBodyAccJerk_mean_X", "tBodyAccJerk_mean_Y", "tBodyAccJerk_mean_Z", "tBodyAccJerk_std_X", "tBodyAccJerk_std_Y", "tBodyAccJerk_std_Z", "tBodyGyro_mean_X", "tBodyGyro_mean_Y", "tBodyGyro_mean_Z", "tBodyGyro_std_X", "tBodyGyro_std_Y", "tBodyGyro_std_Z", "tBodyGyroJerk_mean_X", "tBodyGyroJerk_mean_Y", "tBodyGyroJerk_mean_Z", "tBodyGyroJerk_std_X", "tBodyGyroJerk_std_Y", "tBodyGyroJerk_std_Z", "tBodyAccMag_mean", "tBodyAccMag_std", "tGravityAccMag_mean", "tGravityAccMag_std", "tBodyAccJerkMag_mean", "tBodyAccJerkMag_std", "tBodyGyroMag_mean", "tBodyGyroMag_std", "tBodyGyroJerkMag_mean", "tBodyGyroJerkMag_std", "fBodyAcc_mean_X", "fBodyAcc_mean_Y", "fBodyAcc_mean_Z", "fBodyAcc_std_X", "fBodyAcc_std_Y", "fBodyAcc_std_Z", "fBodyAcc_meanFreq_X", "fBodyAcc_meanFreq_Y", "fBodyAcc_meanFreq_Z", "fBodyAccJerk_mean_X", "fBodyAccJerk_mean_Y", "fBodyAccJerk_mean_Z", "fBodyAccJerk_std_X", "fBodyAccJerk_std_Y", "fBodyAccJerk_std_Z", "fBodyAccJerk_meanFreq_X", "fBodyAccJerk_meanFreq_Y", "fBodyAccJerk_meanFreq_Z", "fBodyGyro_mean_X", "fBodyGyro_mean_Y", "fBodyGyro_mean_Z", "fBodyGyro_std_X", "fBodyGyro_std_Y", "fBodyGyro_std_Z", "fBodyGyro_meanFreq_X", "fBodyGyro_meanFreq_Y", "fBodyGyro_meanFreq_Z", "fBodyAccMag_mean", "fBodyAccMag_std", "fBodyAccMag_meanFreq", "fBodyAccJerkMag_mean", "fBodyAccJerkMag_std", "fBodyAccJerkMag_meanFreq", "fBodyGyroMag_mean", "fBodyGyroMag_std", "fBodyGyroMag_meanFreq", "fBodyGyroJerkMag_mean", "fBodyGyroJerkMag_std", "fBodyGyroJerkMag_meanFreq", "angle(tBodyAccMean,gravity)", "angle(tBodyAccJerkMean),gravityMean)", "angle(tBodyGyroMean,gravityMean), "angle(tBodyGyroJerkMean,gravityMean)", "angle(X,gravityMean)", "angle(Y,gravityMean)", "angle(Z,gravityMean)" 

The column names for each of the measured variables were altered slightly from the original names. They were reformatted into more readable formats. Specifically, all "-" were converted to "_", all extraneous "()" were removed, and duplications of the word "Body" were removed. The abbreviations in the column names were left "as-is" because the names would be too long for easy comprehension with unabreviated words. The abbreviations are listed below:
t - time domain signal
f - frequency domain signal
Acc - Accelerometer
Gyro - Gyroscope
Mag - Magnitude
std - standard deviation
Freq - frequency
X/Y/Z - Direction of movement

###SubjectID

A qualitiative descriptor identifying which subject the data is related to. 

Class: Interger
Summary: 1-30; qualitative values
Unit: No unit of meausre
Origin: These values were included in the subject_test and subject_train tables. Each row gives the ID number of the subject who completed the acitivty measured in the respective rows of X_test and X_train.  

###ActivityNumber

A qualitative descriptor identifying which activity the data is related to. 

Class: Interger
Summary: 1-6; qualitative values
Unit: No unit of meausre
Origin: These values were included in the y_test and y_train tables. Each row gives the activity number of the acitivty measured in the respective rows of X_test and X_train. 

###ActivityLabel

A qualitative descriptor identifying which activity the data is related to. 

Class: Factor
Summary: 1: LAYING 2: SITTING 3: STANDING 4: WALKING 5: WALKING_DOWNSTAIRS 6: WALKING_UPSTAIRS
Unit: No unit of meausre
Origin: These values were joined with the data table from the activity_labels table based on the Activity Number listed in both tables. 

###"tBodyAcc_mean_X"

Mean of the time domain signal for Body Acceleration in the X direction. 

Class: Numeric
Summary: 
    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.2216  0.2712  0.2770  0.2743  0.2800  0.3015 
Unit: No units because data is normalized on a [-1,1] scale. 

###"tBodyAcc_mean_Y"

Mean of the time domain signal for Body Acceleration in the Y direction.

Class: Numeric
Summary: 
     Min.   1st Qu.    Median    Mean     3rd Qu.    Max. 
-0.040510 -0.020020 -0.017260 -0.017880 -0.014940 -0.001308
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAcc_mean_Z"

Mean of the time domain signal for Body Acceleration in the Z direction.

Class: Numeric
Summary: 
    Min.  1st Qu.  Median    Mean     3rd Qu.    Max. 
-0.15250 -0.11210 -0.10820 -0.10920 -0.10440 -0.07538
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAcc_std_X"

Standard Deviation of the time domain signal for Body Acceleration in the X direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median    Mean  3rd Qu.  Max. 
-0.9961 -0.9799 -0.7526 -0.5577 -0.1984  0.6269 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAcc_std_Y"

Standard Deviation of the time domain signal for Body Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.    1st Qu.   Median    Mean   3rd Qu.    Max. 
-0.99020 -0.94210 -0.50900 -0.46050 -0.03077  0.61690 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAcc_std_Z"

Standard Deviation of the time domain signal for Body Acceleration in the Z direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median  Mean   3rd Qu.    Max. 
-0.9877 -0.9498 -0.6518 -0.5756 -0.2306  0.6090 
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAcc_mean_X"

Mean of the time domain signal for Gravity Acceleration in the X direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median  Mean   3rd Qu.    Max. 
-0.6800  0.8376  0.9208  0.6975  0.9425  0.9745
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAcc_mean_Y"

Mean of the time domain signal for Gravity Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.     1st Qu.  Median    Mean   3rd Qu.    Max. 
-0.47990 -0.23320 -0.12780 -0.01621  0.08773  0.95660
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAcc_mean_Z"

Mean of the time domain signal for Gravity Acceleration in the Z direction.

Class: Numeric
Summary: 
  Min.     1st Qu.  Median    Mean   3rd Qu.    Max. 
-0.49510 -0.11730  0.02384  0.07413  0.14950  0.95790
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAcc_std_X"

Standard Deviation of the time domain signal for Gravity Acceleration in the X direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median    Mean  3rd Qu.   Max. 
-0.9968 -0.9825 -0.9695 -0.9638 -0.9509 -0.8296
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAcc_std_Y"

Standard Deviation of the time domain signal for Gravity Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median    Mean  3rd Qu.   Max. 
-0.9942 -0.9711 -0.9590 -0.9524 -0.9370 -0.6436 
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAcc_std_Z"

Standard Deviation of the time domain signal for Gravity Acceleration in the Z direction.

Class: Numeric
Summary: 
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.9910 -0.9605 -0.9450 -0.9364 -0.9180 -0.6102
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerk_mean_X"

Mean of the time domain signal for Body Jerk Acceleration in the X direction.

Class: Numeric
Summary: 
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.04269 0.07396 0.07640 0.07947 0.08330 0.13020
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerk_mean_Y"

Mean of the time domain signal for Body Jerk Acceleration in the Y direction.

Class: Numeric
Summary: 
    Min.      1st Qu.    Median      Mean     3rd Qu.     Max. 
-0.0386900  0.0004664  0.0094700  0.0075650  0.0134000  0.0568200 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerk_mean_Z"

Mean of the time domain signal for Body Jerk Acceleration in the Z direction.

Class: Numeric
Summary: 
    Min.    1st Qu.   Median     Mean     3rd Qu.    Max. 
-0.067460 -0.010600 -0.003861 -0.004953  0.001958  0.038050 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerk_std_X"

Standard Deviation of the time domain signal for Body Jerk Acceleration in the X direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9946 -0.9832 -0.8104 -0.5949 -0.2233  0.5443
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerk_std_Y"

Standard Deviation of the time domain signal for Body Jerk Acceleration in the Y direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9895 -0.9724 -0.7756 -0.5654 -0.1483  0.3553 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerk_std_Z"

Standard Deviation of the time domain signal for Body Jerk Acceleration in the Z direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.99330 -0.98270 -0.88370 -0.73600 -0.51210  0.03102 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyro_mean_X"

Mean of the time domain signal for Body Gyroscopic Movement in the X direction.

Class: Numeric
Summary: 
   Min    1st Qu.  Median    Mean    3rd Qu.    Max. 
-0.20580 -0.04712 -0.02871 -0.03244 -0.01676  0.19270 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyro_mean_Y"

Mean of the time domain signal for Body Gyroscopic Movement in the Y direction.

Class: Numeric
Summary: 
   Min    1st Qu.  Median    Mean    3rd Qu.    Max. 
-0.20420 -0.08955 -0.07318 -0.07426 -0.06113  0.02747  
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyro_mean_Z"

Mean of the time domain signal for Body Gyroscopic Movement in the Z direction.

Class: Numeric
Summary: 
   Min    1st Qu.  Median    Mean    3rd Qu.    Max. 
-0.07245  0.07475  0.08512  0.08744  0.10180  0.17910  
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyro_std_X"

Standard Deviation of the time domain signal for Body Gyroscopic Movement in the X direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9943 -0.9735 -0.7890 -0.6916 -0.4414  0.2677 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyro_std_Y"

Standard Deviation of the time domain signal for Body Gyroscopic Movement in the Y direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9942 -0.9629 -0.8017 -0.6533 -0.4196  0.4765 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyro_std_Z"

Standard Deviation of the time domain signal for Body Gyroscopic Movement in the Z direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9855 -0.9609 -0.8010 -0.6164 -0.3106  0.5649 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroJerk_mean_X"

Mean of the time domain signal for Body Jerk Gyroscopic Movement in the X direction.

Class: Numeric
Summary: 
   Min    1st Qu.  Median    Mean    3rd Qu.    Max. 
-0.15720 -0.10320 -0.09868 -0.09606 -0.09110 -0.02209 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroJerk_mean_Y"

Mean of the time domain signal for Body Jerk Gyroscopic Movement in the Y direction.

Class: Numeric
Summary: 
   Min    1st Qu.  Median    Mean    3rd Qu.    Max. 
-0.07681 -0.04552 -0.04112 -0.04269 -0.03842 -0.01320  
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroJerk_mean_Z"

Mean of the time domain signal for Body Jerk Gyroscopic Movement in the Z direction.

Class: Numeric
Summary: 
   Min      1st Qu.   Median     Mean     3rd Qu.    Max. 
-0.092500 -0.061720 -0.053430 -0.054800 -0.048980 -0.006941 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroJerk_std_X"

Standard Deviation of the time domain signal for Body Jerk Gyroscopic Movement in the X direction.

Class: Numeric
Summary: 
   Min  1st Qu. Median   Mean    3rd Qu.  Max. 
-0.9965 -0.9800 -0.8396 -0.7036 -0.4629  0.1791 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroJerk_std_Y"

Standard Deviation of the time domain signal for Body Jerk Gyroscopic Movement in the Y direction.

Class: Numeric
Summary: 
   Min  1st Qu. Median   Mean    3rd Qu.  Max. 
-0.9971 -0.9832 -0.8942 -0.7636 -0.5861  0.2959 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroJerk_std_Z"

Standard Deviation of the time domain signal for Body Jerk Gyroscopic Movement in the Z direction.

Class: Numeric
Summary: 
   Min  1st Qu. Median   Mean    3rd Qu.  Max. 
-0.9954 -0.9848 -0.8610 -0.7096 -0.4741  0.1932 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccMag_mean"

Mean of the time domain signal for the Magnitude of Body Acceleration.

Class: Numeric
Summary: 
   Min  1st Qu. Median   Mean    3rd Qu.  Max. 
-0.9865 -0.9573 -0.4829 -0.4973 -0.0919  0.6446 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccMag_std"

Standard Deviation of the time domain signal for the Magnitude of Body Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9865 -0.9430 -0.6074 -0.5439 -0.2090  0.4284
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAccMag_mean"

Mean of the time domain signal for the Magnitude of Gravity Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9865 -0.9573 -0.4829 -0.4973 -0.0919  0.6446
Unit: No units because data is normalized on a [-1,1] scale.

###"tGravityAccMag_std"

Standard Deviation of the time domain signal for the Magnitude of Gravity Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9865 -0.9430 -0.6074 -0.5439 -0.2090  0.4284 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerkMag_mean"

Mean of the time domain signal for the Magnitude of Body Jerk Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9928 -0.9807 -0.8168 -0.6079 -0.2456  0.4345  
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyAccJerkMag_std"

Standard Deviation of the time domain signal for the Magnitude of Body Jerk Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9946 -0.9765 -0.8014 -0.5842 -0.2173  0.4506 
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroMag_mean"

Mean of the time domain signal for the Magnitude of Gyroscopic Body Movement.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9807 -0.9461 -0.6551 -0.5652 -0.2159  0.4180   
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroMag_std"

Standard Deviation of the time domain signal for the Magnitude of Gyroscopic Body Movement.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9814 -0.9476 -0.7420 -0.6304 -0.3602  0.3000   
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroJerkMag_mean"

Mean of the time domain signal for the Magnitude of Gyroscopic Body Jerk Movement.

Class: Numeric
Summary: 
   Min    1st Qu.   Median    Mean   3rd Qu.  Max. 
-0.99730 -0.98520 -0.86480 -0.73640 -0.51190  0.08758   
Unit: No units because data is normalized on a [-1,1] scale.

###"tBodyGyroMag_std"

Standard Deviation of the time domain signal for the Magnitude of Gyroscopic Body Jerk Movement.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9977 -0.9805 -0.8809 -0.7550 -0.5767  0.2502   
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAcc_mean_X"

Mean of the frequency domain signal for Body Acceleration in the X direction. 

Class: Numeric
Summary: 
   Min. 1st Qu.  Median  Mean   3rd Qu.    Max. 
-0.9952 -0.9787 -0.7691 -0.5758 -0.2174  0.5370
Unit: No units because data is normalized on a [-1,1] scale. 

###"fBodyAcc_mean_Y"

Mean of the frequency domain signal for Body Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.   1st Qu.    Median    Mean   3rd Qu.    Max. 
-0.98900 -0.95360 -0.59500 -0.48870 -0.06341  0.52420 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAcc_mean_Z"

Mean of the frequency domain signal for Body Acceleration in the Z direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9895 -0.9619 -0.7236 -0.6297 -0.3183  0.2807 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAcc_std_X"

Standard Deviation of the frequency domain signal for Body Acceleration in the X direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median    Mean  3rd Qu.  Max. 
-0.9966 -0.9820 -0.7470 -0.5522 -0.1966  0.6585 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAcc_std_Y"

Standard Deviation of the frequency domain signal for Body Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.    1st Qu.   Median    Mean   3rd Qu.    Max. 
-0.99070 -0.94040 -0.51340 -0.48150 -0.07913  0.56020
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAcc_std_Z"

Standard Deviation of the frequency domain signal for Body Acceleration in the Z direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median  Mean   3rd Qu.    Max. 
-0.9872 -0.9459 -0.6441 -0.5824 -0.2655  0.6871 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAcc_meanFreq_X"

Weighted Average of the frequency domain signal for Body Acceleration in the X direction. 

Class: Numeric
Summary: 
   Min.   1st Qu.  Median     Mean   3rd Qu.    Max. 
-0.63590 -0.39170 -0.25730 -0.23230 -0.06105  0.15910 
Unit: No units because data is normalized on a [-1,1] scale. 

###"fBodyAcc_meanFreq_Y"

Weighted Average of the frequency domain signal for Body Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.      1st Qu.    Median    Mean     3rd Qu.    Max. 
-0.379500 -0.081310  0.007855  0.011530  0.086280  0.466500  
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAcc_meanFreq_Z"

Weighted Average of the frequency domain signal for Body Acceleration in the Z direction.

Class: Numeric
Summary: 
  Min.    1st Qu.  Median   Mean     3rd Qu.    Max. 
-0.52010 -0.03629  0.06582  0.04372  0.17540  0.40250 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_mean_X"

Mean of the frequency domain signal for Body Jerk Acceleration in the X direction.

Class: Numeric
Summary: 
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.9946 -0.9828 -0.8126 -0.6139 -0.2820  0.4743
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_mean_Y"

Mean of the frequency domain signal for Body Jerk Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9894 -0.9725 -0.7817 -0.5882 -0.1963  0.2767 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_mean_Z"

Mean of the frequency domain signal for Body Jerk Acceleration in the Z direction.

Class: Numeric
Summary: 
  Min.  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9920 -0.9796 -0.8707 -0.7144 -0.4697  0.1578
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_std_X"

Standard Deviation of the frequency domain signal for Body Jerk Acceleration in the X direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9951 -0.9847 -0.8254 -0.6121 -0.2475  0.4768
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_std_Y"

Standard Deviation of the frequency domain signal for Body Jerk Acceleration in the Y direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9905 -0.9737 -0.7852 -0.5707 -0.1685  0.3498 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_std_Z"

Standard Deviation of the frequency domain signal for Body Jerk Acceleration in the Z direction.

Class: Numeric
Summary: 
   Min      1st Qu.   Median      Mean    3rd Qu.    Max. 
-0.993100 -0.983700 -0.895100 -0.756500 -0.543800 -0.006236
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_meanFreq_X"

Weighted Average of the frequency domain signal for Body Jerk Acceleration in the X direction.

Class: Numeric
Summary: 
   Min.   1st Qu.  Median     Mean   3rd Qu.    Max. 
-0.57600 -0.28970 -0.06091 -0.06910  0.17660  0.33140
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_meanFreq_Y"

Weighted Average of the frequency domain signal for Body Jerk Acceleration in the Y direction.

Class: Numeric
Summary: 
  Min.    1st Qu.   Median    Mean   3rd Qu.    Max. 
-0.60200 -0.39750 -0.23210 -0.22810 -0.04721  0.19570
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerk_meanFreq_Z"

Weighted Average of the frequency domain signal for Body Jerk Acceleration in the Z direction.

Class: Numeric
Summary: 
  Min.    1st Qu.   Median    Mean   3rd Qu.    Max. 
-0.62760 -0.30870 -0.09187 -0.13760  0.03858  0.23010 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_mean_X"

Mean of the frequency domain signal for Body Gyroscopic Movement in the X direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean   3rd Qu.  Max. 
-0.9931 -0.9697 -0.7300 -0.6367 -0.3387  0.4750  
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_mean_Y"

Mean of the frequency domain signal for Body Gyroscopic Movement in the Y direction.

Class: Numeric
Summary: 
  Min    1st Qu. Median   Mean  3rd Qu.    Max. 
-0.9940 -0.9700 -0.8141 -0.6767 -0.4458  0.3288 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_mean_Z"

Mean of the frequency domain signal for Body Gyroscopic Movement in the Z direction.

Class: Numeric
Summary: 
  Min   1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9860 -0.9624 -0.7909 -0.6044 -0.2635  0.4924   
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_std_X"

Standard Deviation of the frequency domain signal for Body Gyroscopic Movement in the X direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9947 -0.9750 -0.8086 -0.7110 -0.4813  0.1966
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_std_Y"

Standard Deviation of the frequency domain signal for Body Gyroscopic Movement in the Y direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9944 -0.9602 -0.7964 -0.6454 -0.4154  0.6462
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_std_Z"

Standard Deviation of the frequency domain signal for Body Gyroscopic Movement in the Z direction.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.    Max. 
-0.9867 -0.9643 -0.8224 -0.6577 -0.3916  0.5225 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_meanFreq_X"

Weighted Average of the frequency domain signal for Body Gyroscopic Movement in the X direction.

Class: Numeric
Summary: 
     Min    1st Qu.   Median      Mean    3rd Qu.    Max. 
-0.395800 -0.213400 -0.115500 -0.104600  0.002655  0.249200 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_meanFreq_Y"

Weighted Average of the frequency domain signal for Body Gyroscopic Movement in the Y direction.

Class: Numeric
Summary: 
   Min    1st Qu.   Median   Mean    3rd Qu.    Max. 
-0.66680 -0.29430 -0.15790 -0.16740 -0.04269  0.27310 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyro_meanFreq_Z"

Weighted Average of the frequency domain signal for Body Gyroscopic Movement in the Z direction.

Class: Numeric
Summary: 
  Min     1st Qu.  Median   Mean     3rd Qu.    Max. 
-0.50750 -0.15480 -0.05081 -0.05718  0.04152  0.37710   
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccMag_mean"

Mean of the frequency domain signal for the Magnitude of Body Acceleration.

Class: Numeric
Summary: 
   Min  1st Qu. Median   Mean    3rd Qu.  Max. 
-0.9868 -0.9560 -0.6703 -0.5365 -0.1622  0.5866 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccMag_std"

Standard Deviation of the frequency domain signal for the Magnitude of Body Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9876 -0.9452 -0.6513 -0.6210 -0.3654  0.1787
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccMag_meanFreq"

Weighted Average of the frequency domain signal for the Magnitude of Body Acceleration.

Class: Numeric
Summary: 
   Min    1st Qu.   Median   Mean    3rd Qu.  Max. 
-0.31230 -0.01475  0.08132  0.07613  0.17440  0.43580 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerkMag_mean"

Mean of the frequency domain signal for the Magnitude of Body Jerk Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9940 -0.9770 -0.7940 -0.5756 -0.1872  0.5384  
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerkMag_std"

Standard Deviation of the frequency domain signal for the Magnitude of Body Jerk Acceleration.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9944 -0.9752 -0.8126 -0.5992 -0.2668  0.3163  
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyAccJerkMag_meanFreq"

Weighted Average of the frequency domain signal for the Magnitude of Body Jerk Acceleration.

Class: Numeric
Summary: 
   Min    1st Qu.   Median    Mean   3rd Qu.   Max. 
-0.12520  0.04527  0.17200  0.16250  0.27590  0.48810
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyroMag_mean"

Mean of the frequency domain signal for the Magnitude of Gyroscopic Body Movement.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9865 -0.9616 -0.7657 -0.6671 -0.4087  0.2040   
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyroMag_std"

Standard Deviation of the frequency domain signal for the Magnitude of Gyroscopic Body Movement.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9815 -0.9488 -0.7727 -0.6723 -0.4277  0.2367 
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyroMag_meanFreq"

Weighted Average of the frequency domain signal for the Magnitude of Gyroscopic Body Movement.

Class: Numeric
Summary: 
   Min    1st Qu.   Median   Mean    3rd Qu.  Max. 
-0.45660 -0.16950 -0.05352 -0.03603  0.08228  0.40950   
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyroJerkMag_mean"

Mean of the frequency domain signal for the Magnitude of Gyroscopic Body Jerk Movement.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.  Max. 
-0.9976 -0.9813 -0.8779 -0.7564 -0.5831  0.1466    
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyroJerkMag_std"

Standard Deviation of the frequency domain signal for the Magnitude of Gyroscopic Body Jerk Movement.

Class: Numeric
Summary: 
   Min   1st Qu. Median   Mean   3rd Qu.  Max. 
-0.9976 -0.9802 -0.8941 -0.7715 -0.6081  0.2878  
Unit: No units because data is normalized on a [-1,1] scale.

###"fBodyGyroJerkMag_meanFreq"

Weighted Average of the frequency domain signal for the Magnitude of Gyroscopic Body Jerk Movement.

Class: Numeric
Summary: 
   Min    1st Qu.   Median    Mean   3rd Qu.  Max. 
-0.18290  0.05423  0.11160  0.12590  0.20810  0.42630   
Unit: No units because data is normalized on a [-1,1] scale.

###"angle(tBodyAccMean,gravity)"

The angle between the vectors representing the Mean of the time domain signinals for Body Acceleration and gravity.

Class: Numeric
Summary: 
   Min      1st Qu.   Median    Mean      3rd Qu.  Max. 
-0.163000 -0.011010  0.007878  0.006556  0.024390  0.129200   
Unit: No units because data is normalized on a [-1,1] scale.

###"angle(tBodyAccJerkMean),gravityMean)"

The angle between the vectors representing the Mean of the time domain signinals for Body Jerk Acceleration and the Mean of gravity.

Class: Numeric
Summary: 
   Min        1st Qu.   Median      Mean      3rd Qu.     Max. 
-0.1206000 -0.0211700  0.0031360  0.0006439  0.0220900  0.2033000   
Unit: No units because data is normalized on a [-1,1] scale.

###"angle(tBodyGyroMean,gravityMean)"

The angle between the vectors representing the Mean of the time domain signinals for Body Gyroscopic Measure and the Mean of gravity.

Class: Numeric
Summary: 
   Min    1st Qu.   Median    Mean   3rd Qu.  Max. 
-0.38930 -0.01977  0.02087  0.02193  0.06460  0.44410   
Unit: No units because data is normalized on a [-1,1] scale.

###"angle(tBodyGyroJerkMean,gravityMean)"

The angle between the vectors representing the Mean of the time domain signinals for Body Jerk Gyroscopic Measure and the Mean of gravity.

Class: Numeric
Summary: 
   Min    1st Qu.   Median    Mean   3rd Qu.  Max. 
-0.22370 -0.05613 -0.01602 -0.01137  0.03200  0.18240  
Unit: No units because data is normalized on a [-1,1] scale.

###"angle(X,gravityMean)"

The angle between the vectors representing the X direction and the Mean of gravity.

Class: Numeric
Summary: 
   Min  1st Qu.  Median   Mean  3rd Qu.  Max. 
-0.9471 -0.7907 -0.7377 -0.5243 -0.5823  0.7378 
Unit: No units because data is normalized on a [-1,1] scale.

###"angle(Y,gravityMean)"

The angle between the vectors representing the Y direction and the Mean of gravity.

Class: Numeric
Summary: 
    Min   1st Qu.   Median    Mean   3rd Qu.   Max. 
-0.87460  0.02191  0.17140  0.07865  0.24340  0.42480 
Unit: No units because data is normalized on a [-1,1] scale.

###"angle(Z,gravityMean)"

The angle between the vectors representing the Z direction and the Mean of gravity.

Class: Numeric
Summary: 
     Min    1st Qu.    Median     Mean    3rd Qu.    Max. 
-0.873600 -0.083910  0.005079 -0.040440  0.106200  0.390400 
Unit: No units because data is normalized on a [-1,1] scale.

##Sources
Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

